### PR TITLE
Add a heading variable to navigation.html

### PR DESCRIPTION
**Pull request by ClodoaldoPinto**
I have more than one project and need to change the heading text in the navigation.html template each time I want to build one of them. Say from:

    <h3>A Project</h3>

To:

    <h3>Another Project</h3>

### CODE REVIEW

**Comment by bitprophet** [comment]
Do you have a link to an example of this kind of setup? I _think_ I get what you're going for but not entirely sure.

**Comment by ClodoaldoPinto** [comment]
I just published these two tutorials:

http://wsgi.tutorial.codepoint.net/
http://cgi.tutorial.codepoint.net/

**Comment by bitprophet** [comment]
I think I see, you're effectively using the navigation header as the site name. Why is this? Why aren't you setting the logo options for each site/repo such that it's just a text logo with this text in it (which IIRC defaults to the sphinx `project` setting's value).

**Comment by ClodoaldoPinto** [comment]
I'm using the navigation header first because I think it is obvious that
the links below are the navigation links, no need to to clarify it. If I
didn't use it I would just delete it. Second I didn't know I could have a
text logo. I will try it.

**Comment by bitprophet** [comment]
Yea as long as you *don't* set `logo`, and *do* have `project = "myproject"` set in `conf.py`, the default templates ought to spit out an H1 or H2 (forget which) with just `<a href="/">myproject</a>` in it. See for example http://www.paramiko.org/index.html - its conf.py doesn't set `logo` in the theme settings at all, but does set  the top level `project` sphinx option.

**Pull request closed without merging**
