### PR TITLE
Navigation sidebar floats next to document

### LINKED ISSUE #44: Float the navigation panel when scrolling
I've had a few pages get long, where having the navigation scroll with the content would make jumping around the docs much more comfortable.

What about something like the Bootstrap docs navigation sidebar?  [There's a good breakdown here](http://www.codingeverything.com/2014/02/BootstrapDocsSideBar.html) that builds the behavior in layers.

Even without attaching a scrollspy to highlight the current location, simply fixing the navigation to scroll with the content would be a nice enhancement.

### PR DESCRIPTION
**Pull request by numberoverzero**
Fixes #44 without implementing a 'collapse' toggle for mobile views (to be completed later).

### CODE REVIEW

**Comment by bitprophet** [comment]
I see a lot of boilerplatey stuff in here (massive gitignore, demo folder, etc) - can you trim that back out, please? Adds a lot of noise :) thanks!

**Comment by numberoverzero** [comment]
Cut out demo and gitignore.  I think it'd be worth adding a gitignore for common stuff, but that can be done in a different PR.  I see the following untracked after testing locally:

    .python-version
    alabaster.egg-info/
    alabaster/__pycache__

The demo folder was in relation to another issue where someone asked for a script to inspect changes when developing - the folder isn't included when distributing because it isn't included in `setup.py`.  I think there's also some value in having an easy way to test without setting up other projects, but again can be part of a different PR.

**Comment by bitprophet** [comment]
Cool, thanks. (My opinion re: gitignores is that few paths are truly gobal enough to deserve project gitignore status, versus `~/.gitexcludes` - e.g. of your 3 untracked files above, I only ever see egg-info on my end :))

For me to do:

* [ ] Test locally
* [ ] Determine how to version this, it's a nontrivial change to just drop on people.
    * If feasible (e.g. if the HTML-level changes aren't that large or are easily templatized), may just make it an opt-in setting at first.

**Comment by bitprophet** [comment]
Finally getting around to this, apologies. At first glance, I like it; tested it out locally with paramiko's site (e.g. changelog page is a good test as it's very long).

Going to poke to see how easily it can be made into an opt-in setting since I really don't have bandwidth for figuring out backwards compatibility versioning crap right now (it's tough with this particular project anyways).

**Comment by bitprophet** [comment]
Yea I think I got that working. It's not great because it adds the feature toggle check in like 3-4 places, but not that terrible either and *seems* to still work the same as it used to when the feature is not opted into.

**Pull request merged**
