### PR TITLE
More configurable colors

### PR DESCRIPTION
**Pull request by ShadowKyogre**
These were written to address #6 . The option names may still need some editing to follow naming conventions of the rest of the options.

Nonetheless, I tried to follow them as closely as possible.

This is the test case python file I used to help discover where some of the styling goes where: https://gist.github.com/ShadowKyogre/1e2aae8f2db0b9cfe604a136907f0e8d

We could probably gather a few more source files to catch other edge cases too.

### CODE REVIEW

**Comment by ShadowKyogre** [comment]
All of the commits here should address all aspects of #6 now. Let me know if there's anything I need to fix!

**Comment by bitprophet** [comment]
Awesome, thanks for this! Will give it a closer look & do any necessary touch-up + merge at next release cycle.

**Comment by bitprophet** [comment]
Diffed the output of one of my alabaster sites, before & after the changes here, as a sanity check (https://gist.github.com/bitprophet/3ba8195c6a5edf59c20a975fffdb73bd) - everything checks out (esp once I noticed you have useful commit messages that explain things, :heart: :heart: :heart:) besides a couple minor easily-fixed typos. (Including one predating this PR that I found trying to figure out whether empty CSS rules are errors or not...)

**Comment by bitprophet** [comment]
Merged, will go out today in 0.7.9, thanks again!

**Pull request merged**
