### PR TITLE
Setuptools: Entry Points

### PR DESCRIPTION
**Pull request by Blendify**
This adds a sphinx entry point as described on http://www.sphinx-doc.org/en/stable/theming.html#distribute-your-theme-as-a-python-package

### CODE REVIEW

**Comment by bitprophet** [comment]
Thanks!

**Comment by bitprophet** [comment]
Seems this is only compatible with some Sphinx versions, the one I'm running locally lacks that method. Looks like added in Sphinx 1.6. I updated things to only run this new method if it appears to exist.

**Comment by Blendify** [comment]
Sorry about the confusion there...

**Comment by bitprophet** [comment]
No worries - and it prompted me to add the project to Travis-CI, and use its matrix to test us against every workable combo of Python version & Sphinx version - so this kind of thing will get caught earlier next time!

**Pull request merged**
