### PR TITLE
Remove Gratipay integration - gratipay has shut down

### PR DESCRIPTION
**Pull request by joealcorn**
Gratipay [shut down](https://gratipay.news/the-end-cbfba8f50981) at the end of 2017. It's a shame because open source sustainability is an important topic. Perhaps instead of removing donate.html, we could extend it to support patreon and open collective? (are there other services?)

### CODE REVIEW

**Comment by bitprophet** [comment]
Weird, I thought this already got nixed but I must be misremembering or recalling their old name-change from Gittip. Thanks for the input!

I like the idea of changing it to something else instead of straight removal, especially since the template name and some of the language is sufficiently generic. May leave this open until I or others have time to really scan the horizon for what's best.

Tho...probably just want to make the setting names & everything else extra-generic so users can plug in whatever they want? May require expecting users to modify their own template, since these sorts of buttons are usually custom HTML tags (like the Gratipay one was.)

**Comment by bitprophet** [comment]
Consensus at sprints today is that we should just move ahead with merging this and worry about re-adding a generic donation.html later.

My main question now (and one that has been long-standing and long-avoided) is how to release this sort of VERY breaking change while ALSO distributing non-breaking changes. We're pinned at >0.7,<0.8 in Sphinx's setup.py, so I've been just incrementing the bugfix number, but that won't fly for this. So we should just pop out a 1.0 probably, have Sphinx eventually require that version (or just be looser, which may be better...I no longer recall why we wanted to tighten it so much) and try to iterate more normally.

**Comment by bitprophet** [comment]
I'll think about this some more and poke around, hopefully we'll figure something out by end of sprints. May go bother any Sphinx people who are here at PyCon to get their opinion.

**Comment by bitprophet** [comment]
Doesn't seem like Sphinx is sprinting this year but I might still put out a call to see if principals happen to be here anyway.

That said I triple checked my old commit that pinned us, and thanks to my habit of detailed commit messages, I can confirm the main point was to prevent a loose pin from meaning users incidentally upgraded past incompatible versions: https://github.com/sphinx-doc/sphinx/pull/1759

So I think what this means is:

- [ ] Another PR to sphinx master to change the pin from `>=0.7,<0.8` to `>=1.0,<2.0`, which would hopefully then get included in Sphinx uh...1.8
- [ ] Merge this
- [ ] Seek out any other outstanding backwards incompat changes and consider them too
- [ ] Bump us to 1.0.0
- [ ] Update my other Sphinx plugins to work with Sphinx 1.7 (it broke Releases for example)
- [ ] Eagerly await Sphinx 1.8

**Comment by joealcorn** [comment]
> how to release this sort of VERY breaking change

It's breaking in the sense that the functionality no longer exists, but having those options in your config shouldn't break the build (as far as I'm aware?) so is it really "breaking"?

**Comment by bitprophet** [comment]
Returning to this while handling #142, #143 - I don't have the bandwidth to handle the planned jump to 1.0 right now, and since we'd probably have wanted to do some version of this anyways, I think I'm just gonna:

- Remove the gratipay-related *output* in donation.html, while leaving the option in place in the conf file (& documented as deprecated) to avoid abovementioned Sphinx errors.
  - Anyone who hasn't yet removed it from their own options will have it mysteriously disappear when they upgrade
  - But since the current output doesn't do anything/go anywhere (it uses `http://gttp.co/v1.js` which is a 404 today) I don't think that's an actual problem anyone can possibly complain about? Unless they're doing a lot of custom styling, I guess. Seems like an edge case & if they're that customized, they'll know to look at our changelog when they upgrade...
- Inject some variant of the code from #143 in its place, namely an arbitrary donation related link/badge.
- Release an 0.7.x as I've been doing.

**Pull request closed without merging**
