### PR TITLE
Allow to set font-size for body and caption text

### PR DESCRIPTION
**Pull request by SVMarshall**
Hello, 
I just added some more options to be able to define the font-size of the body and caption text (it may or may not be useful to everyone). All settings default to the same values than before.

### CODE REVIEW

**Comment by bitprophet** [comment]
Thanks!

I'm probably missing something, but when a user doesn't explicitly override `caption_font_size`/`caption_font_family` wouldn't that generate invalid CSS rules with blank values? If so, probably need to add a few lines in the big nest of assignments at the top of the stylesheet template.

**Comment by SVMarshall** [comment]
You're welcome!

I'm not completely sure about the correctness of this (I'm not really a CSS expert), but I tested it with Firefox, Chrome and Opera and it seems to inherit the value from "body" when empty. Maybe my assumption was wrong.

**Comment by SVMarshall** [comment]
Seems like the way to go is to use the value 'inherit' instead of an empty value. I just updated the config file.

**Comment by bitprophet** [comment]
Good stuff.

**Pull request merged**
