### PR TITLE
Use SVG icons for Travis CI button

### PR DESCRIPTION
**Pull request by lunaryorn**

### CODE REVIEW

**Comment by bitprophet** [comment]
What's the benefit of this exactly? Scales better on higher-DPI displays, or ???

**Comment by lunaryorn** [comment]
Yes. The PNGs look blurry on Retina screens, or when zooming in.

**Comment by bitprophet** [comment]
Sounds good (also - turns out we're already using SVG for the codecov buttons, heh!) Quickly doublechecked and looks good on my system/browser, including zoomed way in. Thanks again!

**Comment by lunaryorn** [comment]
@bitprophet Thanks for merging :blush: and for your awesome work on this beautiful theme :+1:

**Comment by lunaryorn** [comment]
@bitprophet I'm sorry to bring this on the table again, but I'd kindly like to ask whether you could upload a new release to PyPI so that I could update my `requirements.txt` and build my docs with a Retina-ready Travis button?  That'd be awesome to have :blush:

**Comment by bitprophet** [comment]
0.7.8 going up as we speak! Thanks for the nudge, I had been meaning to put it sooner out but got sidetracked (story of my life). Plus: I took hte time to shovel a good dozen or so other pending issues into master, so it's now a big ol release

**Pull request merged**
