### PR TITLE
Classify project as a stable package ready for production

### PR DESCRIPTION
**Pull request by jdufresne**

### CODE REVIEW

**Comment by bitprophet** [comment]
I like this Halloween costume.

**Comment by bitprophet** [comment]
Don't see a way to actually make Travis run a rebase version of this. Not like it matters given the content :D it did prompt me to trim 2.6/3.3 from the travis.yml at least.

**Comment by jdufresne** [comment]
> it did prompt me to trim 2.6/3.3 from the travis.yml at least.

Did you want to officially drop these versions? They are still referenced in a few places. If so, I'm happy to open a PR that removes all 2.6/3.3 references.

**Comment by bitprophet** [comment]
Nah, see the commit message from the travis.yml change, I'm too afeared to officially drop the support just yet, so the removal from travis is more of a band-aid. Sometime soon though, I've dropped it from almost everything else I own. Alabaster requires more care on the release/versioning end due to being required by Sphinx.

**Pull request merged**
